<?php

namespace AdministracionBundle\Repository;

use AppBundle\Api\CollectionRepository;

/**
 * BodegaRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class BodegaRepository extends CollectionRepository
{
}
