<?php

namespace AdministracionBundle\Repository;

use AppBundle\Api\CollectionRepository;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class MaterialRepository extends CollectionRepository
{
}
