<?php

namespace AdministracionBundle\Repository;

use AppBundle\Api\CollectionRepository;

/**
 * ProveedorRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ProveedorRepository extends CollectionRepository
{
}
