doctrine_mongodb:
    connections:
        default:
            server: "mongodb://%database_host%:%database_port%"
            options: {}
    default_database: "%database_name%"
    document_managers:
        default:
            auto_mapping: true