<?php

namespace PanelBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends DocumentRepository
{
}
