<?php

namespace PanelBundle\Repository;

use AppBundle\Api\CollectionRepository;
/**
 * RecursoRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class RecursoRepository extends CollectionRepository
{
}
