<?php

namespace PanelBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * SeccionRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class SeccionRepository extends DocumentRepository
{
    public function validateNombre(array $criteria)
    {
        print_r($criteria);
    }
}
