<?php

namespace InventarioBundle\Repository;

use AppBundle\Api\CollectionRepository;

/**
 * InventarioBodegaRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class InventarioBodegaRepository extends CollectionRepository
{
}
