<?php

namespace InventarioBundle\Repository;

use AppBundle\Api\CollectionRepository;

/**
 * InventarioMaterialRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class InventarioMaterialRepository extends CollectionRepository
{

}
